# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/unicorn/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),unicorn)

$(call add-radio-file-sha1-checked,radio/abl.img,f26dfde740a5ad5c9c75c097c818df6954952b20)
$(call add-radio-file-sha1-checked,radio/aop.img,5de6613806e185a8db8c32aeb063ae4a04e8f1e0)
$(call add-radio-file-sha1-checked,radio/aop_config.img,c5dd0c59cf9682e62e98584afe3196002779f58a)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,3f60f19875a76074bc3b69ab8431aafc57cb5e02)
$(call add-radio-file-sha1-checked,radio/cpucp.img,bce5178626ef37d36149882d5603e0c3e134357e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,7bde69da475ce9ea17af47a7949604f3afa24c42)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,268ffc0d25dbef1b4bb540f74e6f3d6267040229)
$(call add-radio-file-sha1-checked,radio/hyp.img,fc460da915d91c6fdc788d24b171d59fa8323119)
$(call add-radio-file-sha1-checked,radio/imagefv.img,cecaaaeff9ae882e8107053353b26b5e60645907)
$(call add-radio-file-sha1-checked,radio/keymaster.img,81c96cdb21ee95382cebdbc7987434cd8e038acc)
$(call add-radio-file-sha1-checked,radio/modem.img,4d2c8d5b7ab8271cd402ae997f446686c4274c5d)
$(call add-radio-file-sha1-checked,radio/qupfw.img,7f40e0bf364d80a431f2ff159b4727c2572f07a1)
$(call add-radio-file-sha1-checked,radio/shrm.img,6e70ec89d20c7f395b0ba2139898f8a1dde5f0c1)
$(call add-radio-file-sha1-checked,radio/tz.img,05a6f2da1ed0a290cea09fab0642d57e32d90fb4)
$(call add-radio-file-sha1-checked,radio/uefi.img,e4e9bd5d78eec8d85359861ea4981e6d0f17b3fd)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,1894273fa2d0dfb36191b42cee72006ff0bd0446)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,07aba6ea3ef2cfc903b464582bc8a0b7e34933d5)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,81be386ac6b813256b82b1cebf1012a641752ca7)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,f8c75c905816215f9b57c93d238e5676a42088d9)

endif
