# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/unicorn/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),unicorn)

$(call add-radio-file-sha1-checked,radio/abl.img,e1c3560b1fb9705aa27ffb2b1108dc3b03229ef8)
$(call add-radio-file-sha1-checked,radio/aop.img,38c5b5077076936fe094b23cabaa91c52f136e0f)
$(call add-radio-file-sha1-checked,radio/aop_config.img,91b3d43e93995c0ea5b4c5890783aaf59e687804)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,1725e766e3541940eb65c06c6b1b30b4e7a4f7b8)
$(call add-radio-file-sha1-checked,radio/cpucp.img,34e7b76092b23c7f2186580a1cdd99ac38ec3541)
$(call add-radio-file-sha1-checked,radio/devcfg.img,1cf28d58a244edce3dfee27acc686cd3a8e0d1b3)
$(call add-radio-file-sha1-checked,radio/dsp.img,259329c9822fa19d5ba7f6e06794c44ceec3d220)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e1d1c295f5436f1fa84e260bc459287a6022ea8b)
$(call add-radio-file-sha1-checked,radio/hyp.img,254c1906848dfc0a9f38f63010e703e804eb4e73)
$(call add-radio-file-sha1-checked,radio/imagefv.img,9f8a766e8cb4846148b03bc1c12495daab34473d)
$(call add-radio-file-sha1-checked,radio/keymaster.img,1af59100ec42aa1475e8d07a1a34eb64fa618691)
$(call add-radio-file-sha1-checked,radio/modem.img,83e781569de2498639dd1a2b8e05cd85973af99e)
$(call add-radio-file-sha1-checked,radio/qupfw.img,5f9eb53e2cfeb7e72f3a898056360ccb9ab9ffbe)
$(call add-radio-file-sha1-checked,radio/shrm.img,4884e6cb1509942be4c8ac337c76fe11a6621c41)
$(call add-radio-file-sha1-checked,radio/tz.img,ba8a3567a68eac92646d3aac1e3cd518e693cdd2)
$(call add-radio-file-sha1-checked,radio/uefi.img,c6c85c9c16f1670b1140d53763c97468a28c9ff5)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,dc9fd340e31666eb186f83ecbd6e03fbdecab9d9)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,ba20165ced28dca887728c18dedd4135ad492976)
$(call add-radio-file-sha1-checked,radio/xbl.img,075bb3355802209142da7659a078d9676f88fdaf)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,903d41ea49b9d1f0dd8955964007f780271c5519)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,16f497fe82878cfe240301f39a6633bc1cae4526)

endif
